version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - 5000:5000
    environment:
    - FLASK_APP=app.py
    volumes:
      - $PWD:/usr/src/app
    container_name: "ping-pong-elo"
    network_mode: "bridge"