version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
    - FLASK_APP=app.py
    ports:
    - 5000:5000
    volumes:
      - $PWD:/usr/src/app
    network_mode: "bridge"